### ISSUE TITLE
0xAlix2 - AmoMinter can borrow collateral more than what's free/available

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-12-ubiquity-judging#1]
0xAlix2

medium

# AmoMinter can borrow collateral more than what's free/available

## Summary

AmoMinters can borrow collateral from the protocol to earn yield in external protocols like Compound, and Curve, ... This can be done using the `amoMinterBorrow` function, which sends the "amount" of collateral to the targeted AmoMinter. However, this function doesn't check the validity of the borrowed amount, i.e. it doesn't check if the protocol has enough "free" amount before going ahead and sending the collateral.

## Vulnerability Detail

AmoMinter can borrow a collateral amount even if it is included in an unclaimed collateral storage. So if a user calls `redeemDollar` on certain collateral, and an AmoMinter borrows the full amount of collateral, that user won't be able to call `collectRedemption`, forcing him to lose his dollar tokens for nothing in return. As the transferred "borrowed" amount won't consider the unclaimed collateral `unclaimedPoolCollateral[collateralIndex]`.

```solidity
function test_bug_noFreeCollateralCheck() public {
    uint256 _100ETH = 100e18;

    vm.prank(admin);
    ubiquityPoolFacet.setPriceThresholds(1000000, 1000000);

    assertEq(collateralToken.balanceOf(address(ubiquityPoolFacet)), 0);

    vm.prank(user);
    ubiquityPoolFacet.mintDollar(0, _100ETH, 99e18, _100ETH);

    assertEq(
        collateralToken.balanceOf(address(ubiquityPoolFacet)),
        _100ETH
    );

    vm.prank(user);
    ubiquityPoolFacet.redeemDollar(0, 99e18, 90e18);

    assertEq(
        collateralToken.balanceOf(address(ubiquityPoolFacet)),
        _100ETH
    );
    assertEq(ubiquityPoolFacet.freeCollateralBalance(0), 2.98e18);

    vm.prank(address(dollarAmoMinter));
    ubiquityPoolFacet.amoMinterBorrow(_100ETH);

    vm.roll(3);

    vm.prank(user);
    vm.expectRevert("ERC20: transfer amount exceeds balance");
    ubiquityPoolFacet.collectRedemption(0);
}
```

## Impact

Loss of funds (dollar tokens).

## Code Snippet

https://github.com/sherlock-audit/2023-12-ubiquity/blob/main/ubiquity-dollar/packages/contracts/src/dollar/libraries/LibUbiquityPool.sol#L574-L598

## Tool used

Manual Review + vscode

## Recommendation

Add the following `require` statement in the `amoMinterBorrow` function in the `LibUbiquityPool` library.
```solidity
require(
    collateralAmount <= freeCollateralBalance(minterCollateralIndex),
    "Not enough free collateral"
);
```

**Comment by sherlock-admin2** [comment]
1 comment(s) were left on this issue during the judging contest.

**0xLogos** commented:
> amo minter is trusted, imho correctness of amo behavior is vital to protocol solvency and there's no way to safeguard against its bad behavior and keep its functionality because allowing him to withdraw all free collateral barely only protects pending withdrawls

**Comment by molecula451** [comment]
PR Fix Confirmation: https://github.com/ubiquity/ubiquity-dollar/pull/882

**Comment by 0xLogos** [comment]
Escalate
AMO minters are trusted so this should be low/info

**Comment by sherlock-admin2** [comment]
> Escalate
> AMO minters are trusted so this should be low/info

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by juntzhan** [comment]
It's valid, however this issue and many of its duplicates do not describe the issue correctly, please see https://github.com/sherlock-audit/2023-12-ubiquity-judging/issues/117

**Comment by 0xLogos** [comment]
> It's valid, however this issue and many of its duplicates do not describe the issue correctly, please see #117

Agree, this scenario seems more vital. But from sherlock rules [here](https://docs.sherlock.xyz/audits/judging/judging#iii.-some-standards-observed)

>  If it will result in funds being inaccessible for >=1 year, then it would count as a loss of funds and be eligible for a Medium or High designation.

I think AMO minter will return funds much faster. Also there is funds income from depositors that can replenish missing funds. No to mention that scenario is unlikely.

**Comment by nevillehuang** [comment]
- I believe this breaks the intended functionality of the check to ensure sufficient collateral is there for users. 
- While AMO minter is trusted, is funds transfer even controlled by the protocol itself, or by external protocol? Why not make the check more comprehensive to prevent such DoS scenarios in the first place
- Also I don't see any functionality within the contract where funds can be sent back to the contract, so I think it is fair for watsons to assume this check should be in place.

**Comment by 0xLogos** [comment]
> I believe this breaks the intended functionality of the check to ensure sufficient collateral is there for users. 

I think in correct AMO minter there should be more strict check to not only ensure pending redemption can be done, but also pool can be used for new redemtions to maintain peg stability. If pool withdraw all but pending redemption, pending redemptions ill be ok, but pool can't function after that. In that sense I assume minter is trusted to not do this.

> Also I don't see any functionality within the contract where funds can be sent back to the contract

You do not need this functionality, regular transfer to pool address will work just fine

> While AMO minter is trusted, is funds transfer even controlled by the protocol itself, or by external protocol? Why not make the check more comprehensive to prevent such DoS scenarios in the first place

Make this check is good idea, but this notion don't make finding valid medium

**Comment by 0xLogos** [comment]
> > I believe this breaks the intended functionality of the check to ensure sufficient collateral is there for users.
> 
> I think in correct AMO minter there should be more strict check to not only ensure pending redemption can be done, but also pool can be used for new redemtions to maintain peg stability. If minter withdraw all but pending redemption, pending redemptions will be ok, but pool can't function after that. In that sense I assume minter is trusted to not do this and hence do not dos pending redemptions.
> 
> > Also I don't see any functionality within the contract where funds can be sent back to the contract
> 
> You do not need this functionality, regular transfer to pool address will work just fine
> 
> > While AMO minter is trusted, is funds transfer even controlled by the protocol itself, or by external protocol? Why not make the check more comprehensive to prevent such DoS scenarios in the first place
> 
> Make this check is good idea, but this notion don't make finding valid medium

**Comment by ammarvoloder** [comment]
As @nevillehuang said, you could argue that this can break the functionality of the protocol, causing panic. AMO Minters might be trusted and do not have to break the protocol intentionally, but if they borrow to much, and a couple of users are trying to withdraw their money unsuccessfully it might cause panic where suddenly many users are trying to withdraw while AMO Minters would still keep borrowing. I think this is a valid medium since there is a case where it could affect (i.e., prevent) many users (from claiming) and it needs to be checked.

**Comment by osmanozdemir1** [comment]
I agree with the escalation and want to provide an historical example. I thought trusted actors might make mistakes and these should be valid, but Sherlock invalidated these kind of issues. You can check the comment [in this issue](https://github.com/sherlock-audit/2023-09-Gitcoin-judging/issues/589#issuecomment-1778227315).

That issue is rejected just because managers are trusted and Sherlock didn’t care about possible mistakes even though the sponsor accepted and marked it as “will fix”. 

AMO minters here are trusted and this issue should be invalid.

**Comment by ammarvoloder** [comment]
But this issue has nothing to do with AMO Minters being trusted or not. They can operate as usual, borrow and repay, however the situation above could still happen and end users need to be protected from such scenarios

**Comment by osmanozdemir1** [comment]
I agree with you but in previous contests Sherlock assumed that the trusted actor will always be cautious, act perfectly and will not do anything that harms users.

**Comment by ammarvoloder** [comment]
But they can't act perfectly and be cautious if there is no such check. How they are supposed to be cautious if they can't check how much collateral is left in the vault or if they are not aware of borrowing too much, because what exactly is "too much" for them? As I said, they might not be doing anything wrong and still cause an issue. But Sherlock will decide anyways.

**Comment by 0xLogos** [comment]
> How they are supposed to be cautious if they can't check how much collateral is left in the vault

They [can](https://github.com/sherlock-audit/2023-12-ubiquity/blob/d9c39e8dfd5601e7e8db2e4b3390e7d8dff42a8e/ubiquity-dollar/packages/contracts/src/dollar/libraries/LibUbiquityPool.sol#L263-L276) ([facet](https://github.com/sherlock-audit/2023-12-ubiquity/blob/d9c39e8dfd5601e7e8db2e4b3390e7d8dff42a8e/ubiquity-dollar/packages/contracts/src/dollar/facets/UbiquityPoolFacet.sol#L44-L49))

**Comment by Czar102** [comment]
I agree with the escalation, AMO minters can be trusted to maintain liquidity in the protocol and deposit back right when the system would have liquidity issues due to withdrawal requests.

Planning to accept the escalation and consider this a low severity issue.

**Comment by Czar102** [comment]
Result:
Low
Has duplicates

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [0xLogos](https://github.com/sherlock-audit/2023-12-ubiquity-judging/issues/1/#issuecomment-1911742352): accepted

**Comment by molecula451** [comment]
cross-side ref PR by rndqnuu https://github.com/sherlock-audit/2023-12-ubiquity-judging/issues/1#issuecomment-1908590119

**Comment by sherlock-admin** [comment]
The Lead Senior Watson signed off on the fix.
