### ISSUE TITLE
Coinstein - TWAP could be easily to be manipulated because the time window could be 1 second

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-12-ubiquity-judging#101]
Coinstein

medium

# TWAP could be easily to be manipulated because the time window could be 1 second

## Summary
TWAP could be easily to be manipulated because the time window could be 1 second

## Vulnerability Detail
LibTWAPOracle#update can be called every 1 second. 

See LibTWAPOracle.sol#L74.

```solidity
blockTimestamp - ts.pricesBlockTimestampLast > 0
```

If a whale manipulates the curve pool by doing a swap and making the price imbalanced, the price of LUSD and DAI could be very far away from $1.

This issue is similar to a past reward contest (See https://github.com/code-423n4/2022-06-canto-v2-findings/issues/124)

## Impact
User cannot perform MintDollar function call. See

```solidity
    require(
            getDollarPriceUsd() >= poolStorage.mintPriceThreshold,
            "Dollar price too low"
        );
```

or redeemDollar function call. See

```solidity
     require(
            getDollarPriceUsd() <= poolStorage.redeemPriceThreshold,
            "Dollar price too high"
        );
```

if the price is either too high or too low.

## Code Snippet
https://github.com/sherlock-audit/2023-12-ubiquity/blob/main/ubiquity-dollar/packages/contracts/src/dollar/libraries/LibTWAPOracle.sol#L74

## Tool used
Manual Review

## Recommendation
Increase the twap window to at maybe 1800 seconds as longer durations favor the security of the oracle 

Duplicate of #20

**Comment by sherlock-admin2** [comment]
1 comment(s) were left on this issue during the judging contest.

**auditsea** commented:
> The issue describes about TWAP can be manipulated because `update` function can be called anytime and by anyone, thus TWAP period can be as short as 1 block. It seems like a valid issue but after caeful consideration, it's noticed that the TWAP issue does not come from its period but the logic itself is incorrect, thus marking this as Invalid
