### ISSUE TITLE
cergyk - LibTWAPOracle::update temporary redemption DOS if uAD/3CRV metapool has very low liquidity

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-12-ubiquity-judging#105]
cergyk

medium

# LibTWAPOracle::update temporary redemption DOS if uAD/3CRV metapool has very low liquidity

## Summary
If the metapool 3CRV/uAD has very low liquidity, the spot price may be deviated, which means that as a consequence the TWAP value computed is deviated, and when TWAP of uAD is too high, users withdrawals will revert. This causes a DOS on withdrawals until liquidity in the metapool becomes sufficient again

## Vulnerability Detail
We can see in `LibTWAPOracle::update`, the function `IMetapool::get_dy()` is used to retrieve the spot price on averaged balances. The amount in, for which to retrieve amount out is hardcoded to `1 ether`:
https://github.com/sherlock-audit/2023-12-ubiquity/blob/main/ubiquity-dollar/packages/contracts/src/dollar/libraries/LibTWAPOracle.sol#L84-L89

This means that if the liquidity in the pool is less than 0.9 ether of 3CRV, the value returned by `get_dy` will be less than 0.9 ether, and the `redeemThreshold` will not be verified:
https://github.com/sherlock-audit/2023-12-ubiquity/blob/main/ubiquity-dollar/packages/contracts/src/dollar/libraries/LibUbiquityPool.sol#L418-L421

Temporarily blocking withdrawals

## Impact
Withdrawals are temporarily blocked until enough liquidity is added to the metapool

## Tool used

Manual Review

## Recommendation
Use an adaptive parameter for amount in for this estimation, or do not update if the liquidity is too low

**Comment by sherlock-admin2** [comment]
1 comment(s) were left on this issue during the judging contest.

**auditsea** commented:
> get_dy is called with TWAP balances, does not depend on actual balance

**Comment by 0xnirlin** [comment]
Escalate 
It is the protocol's responsibility to provide enough liquidity in the pools, and the figure of 0.9 ether is too low by any means. This is QA/Low at best. 
Also, devs mentioned that they will be providing at least $50k USD of liquidity.

**Comment by nevillehuang** [comment]
@CergyK any comments?

**Comment by CergyK** [comment]
> Also, devs mentioned that they will be providing at least $50k USD of liquidity.

I don't think this was mentionned publicly during the contest 
So if we put that aside, low liquidity is a realistic event during the creation of the pool for example, and could have been a problem for the core functionality of the protocol (in this case mints would have been wrongly Dosed)

I let judges decide if this should be medium or low

**Comment by 0xnirlin** [comment]
@CergyK , also one thing I didn't point out earlier is,  temporary DOS that can protocol recover from easily is an invalid submission according to Sherlock rules, point number 8 :

User experience and design improvement issues: Issues that cause minor inconvenience to users where there is no material loss of funds are not considered valid. Funds are temporarily stuck and can be recovered by the administrator or owner. Also, if a submission is a design opinion/suggestion without any clear indications of loss of funds is not a valid issue.

**Comment by Czar102** [comment]
Agree with the escalation, one can simply add liquidity and the system will work properly (from my understanding).

Planning to consider this a low severity issue.

**Comment by Evert0x** [comment]
Will follow up to close this issue within 24 hours

**Comment by Evert0x** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [0xnirlin](https://github.com/sherlock-audit/2023-12-ubiquity-judging/issues/105/#issuecomment-1909963504): accepted
