### ISSUE TITLE
ZanyBonzy - Quotes from Curve may be subject to manipulation due to `get_virtual_price` read-only reentrancy

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-12-ubiquity-judging#11]
ZanyBonzy

medium

# Quotes from Curve may be subject to manipulation due to `get_virtual_price` read-only reentrancy

## Summary
The `get_dy` makes a call to the `_current_rates()` function, which uses `get_virtual_price()` function. It's known to have a reentrancy risk, which can affect the price if the protocol fetches quotes from pools.
## Vulnerability Detail
The `update` function in the `LibTwapOracle` contract protocol calls the function `get_dy` to obtain a quote from Curve which holds a read-only reentrancy risk. See [here](https://chainsecurity.com/heartbreaks-curve-lp-oracles/) for more info.
## Impact
The read-only reentrancy operation manipulates the updated prices and as a result, the amount minted and redeemed by a user.
## Code Snippet
https://github.com/sherlock-audit/2023-12-ubiquity/blob/d9c39e8dfd5601e7e8db2e4b3390e7d8dff42a8e/ubiquity-dollar/packages/contracts/src/dollar/libraries/LibTWAPOracle.sol#L84
https://github.com/sherlock-audit/2023-12-ubiquity/blob/d9c39e8dfd5601e7e8db2e4b3390e7d8dff42a8e/ubiquity-dollar/packages/contracts/src/dollar/libraries/LibTWAPOracle.sol#L92
https://github.com/curvefi/curve-metapool/blob/bea8df855866cf170d2f197071e80fbc47483656/vyper/metaswap.vy#L333
https://github.com/curvefi/curve-metapool/blob/bea8df855866cf170d2f197071e80fbc47483656/vyper/metaswap.vy#L119
## Tool used
Manual Code Review

## Recommendation
The simplest way to detect the Curve's read-only reentrancy is by calling a reentrancy protected function on the Curve pool, e.g. remove_liquidity() with zero amounts. This will revert if the Curve pool is locked and succeed when not locked without actually altering state in the Curve pool.

**Comment by sherlock-admin2** [comment]
1 comment(s) were left on this issue during the judging contest.

**auditsea** commented:
> Re-entrancy does not take effect here becuase in Curve, token TWAP is used for price calculation and balances in Curve are updated before any liquidity affecting actions happen. Refer to Curve's _update function
