### ISSUE TITLE
r0ck3tz - Missing alignment of storage to 256 may result in excessive gas consumption

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-12-ubiquity-judging#121]
r0ck3tz

medium

# Missing alignment of storage to 256 may result in excessive gas consumption

## Summary

The protocol uses namespaced storage layout [ERC-7201](https://eips.ethereum.org/EIPS/eip-7201) across all contracts but incorrectly defines the storage location.

## Vulnerability Detail

The storage location should be aligned to 256 which is an optimization in anticipation of gas schedule changes after the Verkle state tree migration, which may cause groups of 256 storage slots to become warm all at once.

## Impact

Not aligning storage to 256 will result in significantly higher gas consumption.

## Code Snippet

- https://github.com/sherlock-audit/2023-12-ubiquity/blob/main/ubiquity-dollar/packages/contracts/src/dollar/libraries/LibAccessControl.sol#L17-L20
- https://github.com/sherlock-audit/2023-12-ubiquity/blob/main/ubiquity-dollar/packages/contracts/src/dollar/libraries/LibDiamond.sol#L22-L23
- https://github.com/sherlock-audit/2023-12-ubiquity/blob/main/ubiquity-dollar/packages/contracts/src/dollar/libraries/LibTWAPOracle.sol#L23-L24
- https://github.com/sherlock-audit/2023-12-ubiquity/blob/main/ubiquity-dollar/packages/contracts/src/dollar/libraries/LibUbiquityPool.sol#L26-L29

## Tool used

Manual Review

## Recommendation

It is recommended to align the storage location to 256 by setting the last byte of the hash to 0:
```solidity
& ~bytes32(uint256(0xff))
```

**Comment by sherlock-admin2** [comment]
1 comment(s) were left on this issue during the judging contest.

**auditsea** commented:
> Gas
