### ISSUE TITLE
XDZIBEC - Insufficient Safeguards in Oracle Data Usage

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-12-ubiquity-judging#123]
XDZIBEC

medium

# Insufficient Safeguards in Oracle Data Usage

## Summary
 the contract is relies on `Chainlink's latestRoundData()` for price updates. on a single oracle poses a issue due to the potential for data inaccuracies, either from external manipulation or internal failures 
## Vulnerability Details
The contract use `updateChainLinkCollateralPrice` function that is  directly relies on Chainlink for updating collateral prices. 
and This reliance without additional safeguards or cross-validation mechanisms raises concerns about the risks associated with a single point of failure in price data sourcing  the problem is arise from that the direct call to `Chainlink's latestRoundData()` without additional cross-verification or fallback mechanisms.
 here is the vulnerable part :
```solidity
    /// @inheritdoc IUbiquityPool
    function updateChainLinkCollateralPrice(uint256 collateralIndex) external {
        LibUbiquityPool.updateChainLinkCollateralPrice(collateralIndex);
    }

    /
```
## Impact
The use of incorrect or outdated price data due to oracle failure or manipulation can lead to improper valuation of collateral. This misvaluation could result in significant financial losses for users through incorrect minting, redeeming, and collateral valuations.
## Code Snippet
- https://github.com/sherlock-audit/2023-12-ubiquity/blob/d9c39e8dfd5601e7e8db2e4b3390e7d8dff42a8e/ubiquity-dollar/packages/contracts/src/dollar/facets/UbiquityPoolFacet.sol#L113C5-L119C4 
## Tool used
Manual Review
## Recommendation
- it's need to use a combination of different oracle services to cross-verify the data, 
- and to establish fallback protocols in case the primary oracle fails to provide updated data.

**Comment by sherlock-admin2** [comment]
1 comment(s) were left on this issue during the judging contest.

**auditsea** commented:
> The issue describes about not checking min/max value from Chainlink for data staleness, but this is not required
