### ISSUE TITLE
cergyk - LibTWAPOracle::setPool Dos on setPool by donating a few wei of 3CRV directly to the metapool

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2023-12-ubiquity-judging#14]
cergyk

medium

# LibTWAPOracle::setPool Dos on setPool by donating a few wei of 3CRV directly to the metapool

## Summary
`LibTWAPOracle::setPool` relies on a perfect match between the initial balance of uAD and 3CRV in the pool, which means that a malicious user can front-run the admin call to `setPool` and donate a few wei of 3CRV to the pool in order to make the call revert. 

## Vulnerability Detail
We can see the the admin function `LibTWAPOracle::setPool`, checks that the balances of uAD and 3CRV are perfectly equal:
https://github.com/sherlock-audit/2023-12-ubiquity/blob/main/ubiquity-dollar/packages/contracts/src/dollar/libraries/LibTWAPOracle.sol#L51

This means that a malicious user can front-run the call to setPool by donating a few wei of 3CRV directly to the metapool, in which case the balances will not match. The admin will not be able to set the pool as the function will revert

## Impact
The feature of migrating to a new pool will be DoSed temporarily, as long as the attacker keeps sending a few wei to the metapool contract

## Tool used
Manual Review

## Recommendation
Accept a slight imbalance between the balances of uAD and 3CRV (by a few dollars), in order to make this kind of DoS economically impractical for the attacker

**Comment by sherlock-admin2** [comment]
1 comment(s) were left on this issue during the judging contest.

**auditsea** commented:
> The issue describes about DOSing setPool function by manipulating the Curve pool, but it's assumed that the Curve pool deployment, LP deposit, and setPool will be handled in one tx using multicall structure

**Comment by MLON33** [comment]
Fix: https://github.com/ubiquity/ubiquity-dollar/pull/883

**Comment by molecula451** [comment]
PR Confirmation fix: https://github.com/ubiquity/ubiquity-dollar/pull/883

**Comment by jingyi2811** [comment]
Escalate

By deploying and setting metapool in the same transaction, malicious user cannot DOS attack. This issue is at most LOW.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> By deploying and setting metapool in the same transaction, malicious user cannot DOS attack. This issue is at most LOW.
> 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by 0xLogos** [comment]
Agree with escalation. Also you can donate a few wei of Dollar and fix balance inequality.

**Comment by nevillehuang** [comment]
- If flashbots are considered like @Czar102 previously mentioned, I agree that this issue can be low severity
- If not, this can possibly allow permanent DoS as long as user keep front-running on mainnet and donating funds into the pool, so can possibly be medium severity too

**Comment by Czar102** [comment]
I agree with the escalation. This issue has the same impact as front-running initializers, which is making the deployment useless (easily detectable) without a loss of funds. This impact is not accepted by Sherlock rules as a Medium severity issue, hence planning to consider this a low.
Will modify the guidelines to include a more generalized rule.

Planning to accept the escalation and invalidate the issue.

**Comment by Czar102** [comment]
Result:
Low
Has duplicates

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [jingyi2811](https://github.com/sherlock-audit/2023-12-ubiquity-judging/issues/14/#issuecomment-1909986294): accepted

**Comment by sherlock-admin** [comment]
The protocol team fixed this issue in PR/commit https://github.com/ubiquity/ubiquity-dollar/pull/883.

**Comment by sherlock-admin** [comment]
The Lead Senior Watson signed off on the fix.
