### ISSUE TITLE
bareli - No access control

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-12-ubiquity-judging#191]
bareli

medium

# No access control

## Summary
There is no onlyAdmin modifier in the updateChainLinkCollateralPrice and  amoMinterBorrow.
## Vulnerability Detail
 function updateChainLinkCollateralPrice(uint256 collateralIndex) external {
        LibUbiquityPool.updateChainLinkCollateralPrice(collateralIndex);
    }

function amoMinterBorrow(uint256 collateralAmount) external {
        LibUbiquityPool.amoMinterBorrow(collateralAmount);
    }
## Impact
Any one calls this function and update the function?
## Code Snippet
https://github.com/sherlock-audit/2023-12-ubiquity/blob/main/ubiquity-dollar/packages/contracts/src/dollar/facets/UbiquityPoolFacet.sol#L123

## Tool used

Manual Review

## Recommendation
use onlyowner modifier.

**Comment by sherlock-admin2** [comment]
1 comment(s) were left on this issue during the judging contest.

**auditsea** commented:
> amoMinterBorrow is restriced in library level
