### ISSUE TITLE
GatewayGuardians - Incorrect peg for uAD when protocol is deployed

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-12-ubiquity-judging#221]
GatewayGuardians

high

# Incorrect peg for uAD when protocol is deployed

## Summary
- The developers mentioned that uAD is 100% collateral backed.
![image](https://github.com/sherlock-audit/2023-12-ubiquity-GatewayGuardians/assets/91771249/773f4e8c-a52b-43b4-b35c-8059bf0fb5ff)
 
- To ensure it, they are backing it with an equal amount of 3CRV in the curve pool during deployment.
![image](https://github.com/sherlock-audit/2023-12-ubiquity-GatewayGuardians/assets/91771249/dc3a709a-237b-472e-8fea-5ae541efdc58)

## Vulnerability Detail
- There is a circular dependency that happens when deploying the protocol:
    - To mint uAD from Ubiquity Pool, we need the Curve pool for TWAP.
    - To create the new `uAD-3CRV` Curve Pool, we need to mint uAD from UbiquityPool.
- To solve this issue, the developers intended to directly mint the initial uAD tokens and then supply them with an equal amount of 3CRV tokens to create the curve pool.
- The issue lies in the fact that uAD is worth $1 but the 3CRV token is $1.03.
- Additionally, the value of the 3CRV token increases as the fees get collected in the Curve's 3Pool.
- Therefore, from the beginning, the uAD is pegged to $1.03 instead of $1.

## Impact
- uAD is pegged to $1.03 instead of $1 during deployment.
- The value of 3CRV tokens is $1.03 and rising ([reference](https://coinmarketcap.com/currencies/lp-3pool-curve/)), so you are supplying 10k uAD ($1) with 10k 3CRV ($1.03). 
- The value will be unbalanced: `uAD ($10,000)` and `3CRV ($10,300)`
## Code Snippet
- It is necessary that the amounts are exactly equal to set the pool as TWAP oracle. This is necessitated with the following [condition](https://github.com/sherlock-audit/2023-12-ubiquity/blob/main/ubiquity-dollar/packages/contracts/src/dollar/libraries/LibTWAPOracle.sol#L51):
```solidity
require(_reserve0 == _reserve1, "TWAPOracle: PAIR_UNBALANCED");
```
## Tool used

Manual Review

## Recommendation
- 3CRV is an LP token, not a stablecoin. And uAD maintaining its peg to $1 is quite important for it to qualify as a "stablecoin"
- Hence, the uAD should be backed with a stablecoin, like DAI, USDC, or LUSD to ensure it is pegged to $1

Duplicate of #59

**Comment by sherlock-admin2** [comment]
1 comment(s) were left on this issue during the judging contest.

**auditsea** commented:
> Threasholds can be controlled to hedge LP price deviation, LP price should represent dollar price better than individual underlying token price
