### ISSUE TITLE
Tigerfrake - Unchecked Ownership Transfer Leads to Potential Misuse and Unauthorized Control

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-12-ubiquity-judging#3]
Tigerfrake

high

# Unchecked Ownership Transfer Leads to Potential Misuse and Unauthorized Control

## Summary

The main vulnerability associated with the `transferOwnership()`  function lies in its potential for misuse.  The function has `external visibility` with no access control which means that anyone can call it and take control of the contract and perform harmful actions. 

This could include altering the contract's logic, draining funds, or even deleting the contract entirely.

## Vulnerability Detail

`transferOwnership()` function from `OwnershipFacet` contact:

```Solidity
function transferOwnership(address _newOwner) external onlyOwner {
   require(
       (_newOwner != address(0)),
       "OwnershipFacet: New owner cannot be the zero address"
   );
   LibDiamond.enforceIsContractOwner();
   LibDiamond.setContractOwner(_newOwner);
}
```

### Attack scenario

```Solidity
contract MaliciousContract {
   address payable owner;

   constructor() {
       owner = payable(msg.sender);
   }

   receive() external payable {
       owner.transfer(msg.value);
   }
}
```
And here's how they could deploy and interact with it:

```Solidity
MaliciousContract maliciousContract = new MaliciousContract();
maliciousContract.transferOwnership(address(maliciousContract));
```

- An `attacker` deploys a malicious contract that implements a `fallback` function to drain funds from the victim contract.

- The attacker calls the `transferOwnership()`  function of the victim contract, passing the address of their malicious contract as the ` _newOwner`.

- The `transferOwnership()`  function updates the contract `owner` to the malicious contract's address.

- Now, whenever the victim contract sends `Ether` to the old owner (which might be triggered by certain events within the contract), the `Ether` is instead sent to the attacker's malicious contract due to the `fallback` function.

The attacker can repeatedly trigger these fund transfers, effectively draining all funds from the victim contract.

## Impact

Once the ownership is transferred, the malicious actor has full control over the contract

## Code Snippet

https://github.com/sherlock-audit/2023-12-ubiquity/blob/main/ubiquity-dollar%2Fpackages%2Fcontracts%2Fsrc%2Fdollar%2Ffacets%2FOwnershipFacet.sol#L10-L17

## Tool used

Manual Review
VS code

## Recommendation

> To mitigate this risk, it's crucial to implement proper access controls and to carefully manage who can call sensitive functions like `transferOwnership()`

**Comment by molecula451** [comment]
This is an invalid issue, as the `transferOwnership()` function uses `onlyOwner` modifier, it will always revert, the reason this function it's external its because how the control it's implemented regarding the diamond/facets architecture, on a high level overview it is external, on the inside of the library it's internal

**Comment by sherlock-admin2** [comment]
1 comment(s) were left on this issue during the judging contest.

**auditsea** commented:
> `enforceIsContractOwner` is called before `setContractOwner`
