### ISSUE TITLE
ArmedGoose - Setting new pool will fail in most cases due to strict balance requirement

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-12-ubiquity-judging#35]
ArmedGoose

medium

# Setting new pool will fail in most cases due to strict balance requirement

## Summary
Function `setPool` in [LibTWAPOracle.sol](https://github.com/sherlock-audit/2023-12-ubiquity/blob/main/ubiquity-dollar/packages/contracts/src/dollar/libraries/LibTWAPOracle.sol#L31) requires the pool reserves to be strictly equal. This is unlikely to happen in the real world and because of it, most of the times such call is likely to fail, leaving the protocol nonfunctional.

## Vulnerability Detail
Function `setPool` in `TWAPOracleDollar3poolFacet` calls function of the same name from `LibTWAPOracle`. In line 45,46 and 51, it contains following require statement:

```solidity
        uint256 _reserve0 = uint112(IMetaPool(_pool).balances(0));
        uint256 _reserve1 = uint112(IMetaPool(_pool).balances(1));

        // ensure that there's liquidity in the pair
        require(_reserve0 != 0 && _reserve1 != 0, "TWAPOracle: NO_RESERVES");
        // ensure that pair balance is perfect
        require(_reserve0 == _reserve1, "TWAPOracle: PAIR_UNBALANCED");
```

The `reserve` parameters are taken from a curve metapool. It should be noted, that due to nature of the pool and its usual volatility, it is unlikely to happen that each reserve has equal number of wei anytime, not to mention, that this can be maliciously frontrun too, to prevent the protocol from setting the pool. 

For further reference, this issue resembles a common bug related to slippage, where exact 0 slippage is required, which is also rarely or never met due to natural volatility of liquidity pools, thus transaction with such requirement will fail in most cases.

## Impact
Protocol failing to set a pool is nonfunctional which is a loss for the protocol itself, as it fails to fulfill its main business purpose which is its existence. This is because redeeming and minting dollars relies on call to the oracle, which relies on the pool being set up.

## Code Snippet
```solidity
    function setPool(address _pool, address _curve3CRVToken1) internal {
        require(
            IMetaPool(_pool).coins(0) ==
                LibAppStorage.appStorage().dollarTokenAddress,
            "TWAPOracle: FIRST_COIN_NOT_DOLLAR"
        );
        TWAPOracleStorage storage ts = twapOracleStorage();

        // coin at index 0 is Ubiquity Dollar and index 1 is 3CRV
        require(
            IMetaPool(_pool).coins(1) == _curve3CRVToken1,
            "TWAPOracle: COIN_ORDER_MISMATCH"
        );

        uint256 _reserve0 = uint112(IMetaPool(_pool).balances(0));
        uint256 _reserve1 = uint112(IMetaPool(_pool).balances(1));

        // ensure that there's liquidity in the pair
        require(_reserve0 != 0 && _reserve1 != 0, "TWAPOracle: NO_RESERVES"); 
        // ensure that pair balance is perfect
        require(_reserve0 == _reserve1, "TWAPOracle: PAIR_UNBALANCED"); //@audit unlikely to be met in real world
        ts.priceCumulativeLast = IMetaPool(_pool).get_price_cumulative_last();
        ts.pricesBlockTimestampLast = IMetaPool(_pool).block_timestamp_last();
        ts.pool = _pool;
        // dollar token is inside the diamond
        ts.token1 = _curve3CRVToken1;
        ts.price0Average = 1 ether;
        ts.price1Average = 1 ether;
    }

```

## Tool used

Manual Review

## Recommendation
Do not require to have equal reserves. Take them as they are, or at least make a reasonable threshold of the difference of reserves. However in order to have an accurate TWAP, a time window when the price is periodically updated after appointing new pool might be required once TWAP can be fully relied on.

Duplicate of #14

**Comment by sherlock-admin2** [comment]
1 comment(s) were left on this issue during the judging contest.

**auditsea** commented:
> The issue describes about DOSing setPool function by manipulating the Curve pool, but it's assumed that the Curve pool deployment, LP deposit, and setPool will be handled in one tx using multicall structure
