### ISSUE TITLE
Tendency - Missing Functionality for Withdrawing Accrued Fees in `UbiquityPoolFacet`

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-12-ubiquity-judging#39]
Tendency

medium

# Missing Functionality for Withdrawing Accrued Fees in `UbiquityPoolFacet`

## Summary
There is no functionality in [UbiquityPoolFacet ](https://github.com/sherlock-audit/2023-12-ubiquity/blob/d9c39e8dfd5601e7e8db2e4b3390e7d8dff42a8e/ubiquity-dollar/packages/contracts/src/dollar/facets/UbiquityPoolFacet.sol#L14)for withdrawing accrued fees
## Vulnerability Detail

When minting dollar via [UbiquityPoolFacet::mintDollar](https://github.com/sherlock-audit/2023-12-ubiquity/blob/d9c39e8dfd5601e7e8db2e4b3390e7d8dff42a8e/ubiquity-dollar/packages/contracts/src/dollar/facets/UbiquityPoolFacet.sol#L77-L91) function and when redeeming ubiquity dollar for collateral via [UbiquityPoolFacet::redeemDollar](https://github.com/sherlock-audit/2023-12-ubiquity/blob/d9c39e8dfd5601e7e8db2e4b3390e7d8dff42a8e/ubiquity-dollar/packages/contracts/src/dollar/facets/UbiquityPoolFacet.sol#L93-L104) function, a fee is charged:

https://github.com/sherlock-audit/2023-12-ubiquity/blob/d9c39e8dfd5601e7e8db2e4b3390e7d8dff42a8e/ubiquity-dollar/packages/contracts/src/dollar/libraries/LibUbiquityPool.sol#L357-L364

https://github.com/sherlock-audit/2023-12-ubiquity/blob/d9c39e8dfd5601e7e8db2e4b3390e7d8dff42a8e/ubiquity-dollar/packages/contracts/src/dollar/libraries/LibUbiquityPool.sol#L423-L429

But this charged fee is currently not accounted for in the system and not withdrawable by the contract owner via any functionality in the system, making the collected fees stay stuck in the contract

## Impact
All fees accrued in `ubiquity `pool are not withdrawable
## Code Snippet
https://github.com/sherlock-audit/2023-12-ubiquity/blob/d9c39e8dfd5601e7e8db2e4b3390e7d8dff42a8e/ubiquity-dollar/packages/contracts/src/dollar/libraries/LibUbiquityPool.sol#L326-L386

https://github.com/sherlock-audit/2023-12-ubiquity/blob/d9c39e8dfd5601e7e8db2e4b3390e7d8dff42a8e/ubiquity-dollar/packages/contracts/src/dollar/libraries/LibUbiquityPool.sol#L399-L465
## Tool used

Manual Review

## Recommendation
Add a variable that accounts for accrued fees and a functionality that allows the owner to send out these fees

Duplicate of #36

**Comment by sherlock-admin2** [comment]
1 comment(s) were left on this issue during the judging contest.

**auditsea** commented:
> The goal of fee taken for mint/redeem is to hedge the risk of price deviation
