### ISSUE TITLE
ravikiran.web3 - redeemPriceThreshold & mintPriceThreshold limits the uAD that can be minted or redeemed. The limits should be governed by price itself

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-12-ubiquity-judging#41]
ravikiran.web3

medium

# redeemPriceThreshold & mintPriceThreshold limits the uAD that can be minted or redeemed. The limits should be governed by price itself

## Summary
The redeem and mint prices can be configued by Admin leaving it to the discretion of the admin.
It should be relative to the USD value returned from the 3D curve  pool alone.

## Vulnerability Detail
If relative value of uAD to 3dCurve dollar is greater than 1, more uAD should be mintable.
That means if getDollarPriceUsd() returns value greater than 1, more uAD should be mintable.

If it is less than 1, uAD should be removed from circulation and hence should be redeemable.

But, instead, the value of getDollarPriceUsd() is compared against threshold that are set by the admin.
Now, admin can set the mintPriceThreshold to 0.9 which means more uAD can be minted even when the dollar price is less than 1, say, 0.91 is what was returned by the getDollarPriceUsd().

Similar case applies to redemption.

The relative values of  redeem and mint threshold are also not checked at the time of setting, which means, if intended, admin can reconfigured the circumstances to mint or redeem at his discretion.

## Impact
Although, this may not be intent, there is a scope to configure mint more uAD when the price of dollar is less than uAD and dilute the 
token or make it more expensive by preventing redemption when the uAD is above dollar with the thresholds.

This should not be allowed from the end user's point of view.

## Code Snippet
Refer to the code snippet below for minting

```solidity
 require(
            getDollarPriceUsd() >= poolStorage.mintPriceThreshold,
            "Dollar price too low"
        );
``` 
full function
https://github.com/sherlock-audit/2023-12-ubiquity/blob/main/ubiquity-dollar/packages/contracts/src/dollar/libraries/LibUbiquityPool.sol#L326-L386

Refer to the code snippet below for redeeming

```Solidity
 require(
            getDollarPriceUsd() <= poolStorage.redeemPriceThreshold,
            "Dollar price too high"
        );
```

**Full function:**
https://github.com/sherlock-audit/2023-12-ubiquity/blob/main/ubiquity-dollar/packages/contracts/src/dollar/libraries/LibUbiquityPool.sol#L399-L465

**Setting threshold**
Refer to the below implementation where mintPriceThreshold and redeemPriceThreshold does not enforce any range of values
and also the relationship between the two threshold.

To honour the conditions, newMintPriceThreshold should be greater than redeem threshold. There is nothing stopping the admin from setting these values to any thing at his discretion. 

```solidity
 poolStorage.mintPriceThreshold = newMintPriceThreshold;
 poolStorage.redeemPriceThreshold = newRedeemPriceThreshold;
```

https://github.com/sherlock-audit/2023-12-ubiquity/blob/main/ubiquity-dollar/packages/contracts/src/dollar/libraries/LibUbiquityPool.sol#L768-L778

## Tool used

Manual Review

## Recommendation
The price range should be defined and set for both threshold. Admin should have entitlement to set values, but for only the valid range.

RedeemPrice should allow values representing less than 1, 0.999999 or less
MintPrice should allow values representing above 1.000001

**Comment by sherlock-admin2** [comment]
1 comment(s) were left on this issue during the judging contest.

**auditsea** commented:
> The threashold values are set by admin to hedge Ubiquity Dollar price deviation, thus not have to be governed by price itself
