### ISSUE TITLE
qmdddd - In `addCollateralToken`, there is no existence check for `collateralAddress`, which may lead to overwriting.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-12-ubiquity-judging#43]
qmdddd

high

# In `addCollateralToken`, there is no existence check for `collateralAddress`, which may lead to overwriting.

## Summary

In `addCollateralToken`, there is no existence check for `collateralAddress`, which may lead to overwriting.

## Vulnerability Detail

In `addCollateralToken`, there is no existence check for `collateralAddress`, which may lead to overwriting. 

```solidity
function addCollateralToken(
    address collateralAddress,
    address chainLinkPriceFeedAddress,
    uint256 poolCeiling
) internal {
    UbiquityPoolStorage storage poolStorage = ubiquityPoolStorage();

    uint256 collateralIndex = poolStorage.collateralAddresses.length;

    // add collateral address to all collaterals
    poolStorage.collateralAddresses.push(collateralAddress);

    // for fast collateral address -> collateral idx lookups later
    poolStorage.collateralIndex[collateralAddress] = collateralIndex;
```

If `collateralAddress` is an existing address, the original `collateralIndex` will be overwritten, resulting in data inconsistency.

## Impact

data inconsistency

## Code Snippet

https://github.com/sherlock-audit/2023-12-ubiquity/blob/main/ubiquity-dollar/packages/contracts/src/dollar/libraries/LibUbiquityPool.sol#L629-L642

## Tool used

Manual Review

## Recommendation

Check if `collateralAddress` is already in `poolStorage.collateralAddresses`.

Duplicate of #27

**Comment by sherlock-admin2** [comment]
1 comment(s) were left on this issue during the judging contest.

**auditsea** commented:
> This issue describes about collateral duplication by admin function call, not important
