### ISSUE TITLE
Pet Cloth Turtle - Implementation of EIP-2535 Does Not Fully Match the Specification

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-12-ubiquity-judging#45]
Pet Cloth Turtle

medium

# Implementation of EIP-2535 Does Not Fully Match the Specification

## Summary
The `Diamond` contract implements the EIP-2535 standard, often referred to as the diamond proxy pattern.

The diamond proxy pattern is a proxy design where the functions are separated into multiple smaller 'facet' contracts. By breaking down the implementation contract into multiple facets, it is possible to build larger and more complex applications without exceeding the contract size limit.
`Diamonds` must support inspecting facets and functions by implementing the `IDiamondLoupe` interface and allowing access to its functions. The contract imports this interface but doesn't implement it.

## Vulnerability Detail
The `Diamond` contract  doesn't not implement the `facetAddresses` function 
The `Diamond` contract does not implement the `facets` function.
The `Diamond` contract  does not implement the `facetsAddress` function.
The `Diamond` contract does not implement the `facetFunctionSelector` function 

These functions are expected to be called frequently by tools.

While the deviations from the specification may not be problematic for this particular use case, they may potentially cause errors in clients interacting with the `Diamond ` contract who expect a fully-compliant implementation of `EIP-2535`. For example, tools such as Louper will not work as the function signatures of the functions used to inspect the Diamond do not match the ones from the standard.

## Impact
This could potentially impact the transparency, interoperability, and extensibility of the diamond proxy in the long run.

## Code Snippet
https://github.com/sherlock-audit/2023-12-ubiquity/blob/main/ubiquity-dollar/packages/contracts/src/dollar/Diamond.sol#L24
## Tool used

Manual Review

## Recommendation

Implement the `DiamondLoupe` function for seemless introspection.

**Comment by molecula451** [comment]
Invalid, the repo implements this DiamondLoupe function including:

- facetAddresses
- facetFunctionSelector

at [LibDiamond.sol](https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/contracts/src/dollar/libraries/LibDiamond.sol)

**Comment by sherlock-admin2** [comment]
1 comment(s) were left on this issue during the judging contest.

**auditsea** commented:
> Agree with they will be useful if added, but it's protocol decision
