### ISSUE TITLE
cats - Whale can DOS minting by griefing and directly transferring enough collateral to the contract address

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-12-ubiquity-judging#47]
cats

medium

# Whale can DOS minting by griefing and directly transferring enough collateral to the contract address

## Summary
A whale can DOS minting by griefing and directly transferring enough collateral to the contract address.
## Vulnerability Detail
When we are trying to mint there is a check which requires that the contract's (`balanceOf` collateral - `unclaimedCollateral`) + `collateralNeededForMint` <= `poolCeiling`

https://github.com/sherlock-audit/2023-12-ubiquity/blob/d9c39e8dfd5601e7e8db2e4b3390e7d8dff42a8e/ubiquity-dollar/packages/contracts/src/dollar/libraries/LibUbiquityPool.sol#L371-L375
```javascript
        require(
            freeCollateralBalance(collateralIndex).add(collateralNeeded) <=
                poolStorage.poolCeilings[collateralIndex],
            "Pool ceiling"
        );
```
https://github.com/sherlock-audit/2023-12-ubiquity/blob/d9c39e8dfd5601e7e8db2e4b3390e7d8dff42a8e/ubiquity-dollar/packages/contracts/src/dollar/libraries/LibUbiquityPool.sol#L268-L276

```javascript
    function freeCollateralBalance(
        uint256 collateralIndex
    ) internal view returns (uint256) {
        UbiquityPoolStorage storage poolStorage = ubiquityPoolStorage();
        return
            IERC20(poolStorage.collateralAddresses[collateralIndex])
                .balanceOf(address(this))
                .sub(poolStorage.unclaimedPoolCollateral[collateralIndex]);
    }
```

This can easily become problematic. A whale could directly transfer collateral tokens to the contract's address to inflate the `balanceOf` value and that way DOS the whole minting process of the protocol (even before anyone else has minted anything) until the protocol team doesn't respond and raise the `poolCeiling`, but then again - the ceiling is intended to be amount `N` and this just forces the protocol to raise it to amount `M`.

Of course, depending on the ceiling this could be costly (or not), but it is always a possible vector and we've seen past instances of protocols griefing their competitors.
## Impact
Temporary DOS of minting until protocol raises `poolCeiling`
## Code Snippet
https://github.com/sherlock-audit/2023-12-ubiquity/blob/d9c39e8dfd5601e7e8db2e4b3390e7d8dff42a8e/ubiquity-dollar/packages/contracts/src/dollar/libraries/LibUbiquityPool.sol#L371-L375

https://github.com/sherlock-audit/2023-12-ubiquity/blob/d9c39e8dfd5601e7e8db2e4b3390e7d8dff42a8e/ubiquity-dollar/packages/contracts/src/dollar/libraries/LibUbiquityPool.sol#L268-L276
## Tool used

Manual Review

## Recommendation
Add internal accounting for collateral deposited instead of using `balanceOf(address(this))`:

```diff
    function mintDollar(...) internal collateralEnabled(collateralIndex) returns (...)
    {
        ...
        // take collateral first
        IERC20(poolStorage.collateralAddresses[collateralIndex])
            .safeTransferFrom(msg.sender, address(this), collateralNeeded);

+       poolStorage.totalCollateralDeposited[collateralIndex] = poolStorage.totalCollateralDeposited[collateralIndex] + collateralNeeded;

        // mint Dollars
        IERC20Ubiquity ubiquityDollarToken = IERC20Ubiquity(
            LibAppStorage.appStorage().dollarTokenAddress
        );
        ubiquityDollarToken.mint(msg.sender, totalDollarMint);
    }
```

```diff
function freeCollateralBalance(...) internal view returns (...) { 
     UbiquityPoolStorage storage poolStorage = ubiquityPoolStorage(); 
+     return poolStorage.totalCollateralDeposited[collateralIndex].sub(poolStorage.unclaimedPoolCollateral[collateralIndex];
-        IERC20(poolStorage.collateralAddresses[collateralIndex]) 
-            .balanceOf(address(this)) 
-            .sub(poolStorage.unclaimedPoolCollateral[collateralIndex]); 
 } 
```

Duplicate of #54

**Comment by sherlock-admin2** [comment]
1 comment(s) were left on this issue during the judging contest.

**auditsea** commented:
> It only just cause loss for DOSers, the admin will simply take the amount after increasing poolCeiling and decrease it back to original value
