### ISSUE TITLE
zraxx - For all redemptions, using the same lock (`poolStorage.lastRedeemedBlock`) will block the previous redemptions.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-12-ubiquity-judging#51]
zraxx

medium

# For all redemptions, using the same lock (`poolStorage.lastRedeemedBlock`) will block the previous redemptions.

## Summary

For all redemptions, using the same lock (`poolStorage.lastRedeemedBlock`) will block the previous redemptions.

## Vulnerability Detail

When calling `redeemDollar`, the current block number will be recorded in `poolStorage.lastRedeemedBlock[msg.sender]`.

```solidity
poolStorage.lastRedeemedBlock[msg.sender] = block.number;
```

When withdrawing collateral in function `collectRedemption`, the current block number is required to be the block number recorded plus a delay.

```solidity
require(
    (
        poolStorage.lastRedeemedBlock[msg.sender].add(
            poolStorage.redemptionDelayBlocks
        )
    ) <= block.number,
    "Too soon to collect redemption"
);
```

However, there is only one `lastRedeemedBlock` for a user, which means that the block number being checked in `collectRedemption` is always the block number of the most recent redemption operation. This is where the issue lies. Collateral that was previously (not most recently) redeemed may not be withdrawn on time.

Please consider the following situation:

(1) poolStorage.redemptionDelayBlocks = 10

(2) Bob redeems some collateral X with collateralIndex=0 when the block number is 1000.

(3) When the block number is 1010, Bob redeems some another collateral Y with collateralIndex=1.

(4) Later, when the block number is 1011, bob wants to redeem collateral X because 10 blocks have passed. But this will be reverted since new lastRedeemedBlock equals to 1010, not 1000.

## Impact

Collateral that was previously (not most recently) redeemed may not be withdrawn on time.

## Code Snippet

https://github.com/sherlock-audit/2023-12-ubiquity/blob/main/ubiquity-dollar/packages/contracts/src/dollar/libraries/LibUbiquityPool.sol#L458

https://github.com/sherlock-audit/2023-12-ubiquity/blob/main/ubiquity-dollar/packages/contracts/src/dollar/libraries/LibUbiquityPool.sol#L476-L492

## Tool used

Manual Review

## Recommendation

Set a lock for each redemptions.

Duplicate of #180

**Comment by sherlock-admin2** [comment]
1 comment(s) were left on this issue during the judging contest.

**auditsea** commented:
> It's protocol decision, and not affecting the protocol
