### ISSUE TITLE
blutorque - `addCollateralToken` set default heartbeat to 1 days, can lead to stale prices

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-12-ubiquity-judging#55]
blutorque

medium

# `addCollateralToken` set default heartbeat to 1 days, can lead to stale prices

## Summary
The heartbeat in `LibUbiquityPool` is defined as `collateralPriceFeedStalenessThresholds`, it represent how often price should be update for the given collateral. Tokens such as LUSD, DAI has heartbeat of 3600 seconds, whereas the ubiquityPool uses the 1 days as default. 
If there going to be major price flutuation after last `updateChainLinkCollateralPrice()` call, the pool will update new prices after 1 day instead of an hour. Hence, end up using stale price. 
## Vulnerability Detail
Mentioned above,
## Impact
Ubiquity pools may using stale price
## Code Snippet
https://github.com/sherlock-audit/2023-12-ubiquity/blob/main/ubiquity-dollar/packages/contracts/src/dollar/libraries/LibUbiquityPool.sol#L679
## Tool used

Manual Review

## Recommendation
`setCollateralChainLinkPriceFeed()` passes stalenessThreshold as a parameter, to update heartbeat for a specific collateral. Use this internal function to update the stalenessThreshold along with priceFeed or passed another threshold parameter to `addCollateralToken`. 

Duplicate of #130

**Comment by sherlock-admin2** [comment]
1 comment(s) were left on this issue during the judging contest.

**auditsea** commented:
> This issue describes about retreiving zero index by default when collateralAddress is unknown, but the function is called by admin so no need to be considered
