### ISSUE TITLE
rvierdiiev - LibTWAPOracle can be manipulated

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-12-ubiquity-judging#67]
rvierdiiev

high

# LibTWAPOracle can be manipulated

## Summary
LibTWAPOracle can be manipulated as it doesn't use any window.
## Vulnerability Detail
LibTWAPOracle library is responsible for querying curve pool twap and based on the result [calculate the price of UbiquityDollar](https://github.com/sherlock-audit/2023-12-ubiquity/blob/main/ubiquity-dollar/packages/contracts/src/dollar/libraries/LibTWAPOracle.sol#L159-L164).

Each time, when `update` is called, which [can be called by anyone from facet](https://github.com/sherlock-audit/2023-12-ubiquity/blob/main/ubiquity-dollar/packages/contracts/src/dollar/facets/TWAPOracleDollar3poolFacet.sol#L33) for example, then in case if last prices update was before the last twap update, [function will calculate prices](https://github.com/sherlock-audit/2023-12-ubiquity/blob/main/ubiquity-dollar/packages/contracts/src/dollar/libraries/LibTWAPOracle.sol#L84-L97), based on twap info. Also each time, [it stores current data](https://github.com/sherlock-audit/2023-12-ubiquity/blob/main/ubiquity-dollar/packages/contracts/src/dollar/libraries/LibTWAPOracle.sol#L99-L100) to [use it later for comparison](https://github.com/sherlock-audit/2023-12-ubiquity/blob/main/ubiquity-dollar/packages/contracts/src/dollar/libraries/LibTWAPOracle.sol#L78).

As you can see this function doesn't use any twap window, it only checks changes between current time and last call. And this time period can be long or short. 

Attacker can use this to manipulate the price in one block. 
- attacker does simple small swap just to update `price_cumulative_last` in the curve pool to current values.
- then in same block he will update the price using `TWAPOracleDollar3poolFacet`, to set `ts.priceCumulativeLast` to current values of the twap
- then in same block he will change price in the curve pool
- in next block he just do simple swap just to update `price_cumulative_last` in the pool to current values
- now, when `TWAPOracleDollar3poolFacet.update` is called, then function will calculate price between last 2 blocks, which will give attacker the price that he wanted to receive.

If we look into [`get_twap_balances` function](https://etherscan.io/address/0x5F890841f657d90E081bAbdB532A05996Af79Fe6#code#L290), then we will see, that it will just calculate the difference in balances between to cummulative balances and divide it by the time period. In our case this time period will be just 1 block, which will return us exactly the price that attacker have manipulated by his swap.

In case if attacker controls 2 blocks in a row(validator), then he will be able to now allow any arbitrage and will avoid loss as after attack he will balance pool back.

Currently, the twap is used just to determine if mint or redeem of UbiquityDollar should be allowed. So attacker can get any allowance he needs.

But also protocol team has said, that the twap is going to be used by other services and is really important for them. Without seeing those services i can't say the impact, but it can be severe.
## Impact
Price can be manipulated.
## Code Snippet
Provided above
## Tool used

Manual Review

## Recommendation
The power of twap oracles is the ability to calculate price during some time window. But in such implementation as curve has, you need somehow to query `price_cumulative_last` each time when window closes. Current implementation can't get any protection.

Duplicate of #20

**Comment by sherlock-admin2** [comment]
1 comment(s) were left on this issue during the judging contest.

**auditsea** commented:
> The issue describes about TWAP can be manipulated because `update` function can be called anytime and by anyone, thus TWAP period can be as short as 1 block. It seems like a valid issue but after caeful consideration, it's noticed that the TWAP issue does not come from its period but the logic itself is incorrect, thus marking this as Invalid
