### ISSUE TITLE
rvierdiiev - When contract is paused, then users still can use it

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-12-ubiquity-judging#71]
rvierdiiev

medium

# When contract is paused, then users still can use it

## Summary
When contract is paused, then users still can use it as there are no `whenNotPaused` checks.
## Vulnerability Detail
Admin of protocol can [pause contract](https://github.com/sherlock-audit/2023-12-ubiquity/blob/main/ubiquity-dollar/packages/contracts/src/dollar/facets/AccessControlFacet.sol#L60). In this case all actions should be paused as well to not allow user to make situation even worse.

However, functions inside `LibUbiquityPool` doesn't check `whenNotPaused` modifier. While functions that allow minting/redeeming/borrowing have their own ways to stop functionality this issue states about need to follow one pattern to be able to stop all functions immediately after emergency happened.

Also, maybe `TWAPOracleDollar3poolFacet` contract `consult` and `update` function should also be paused, to not allow price manipulation for integrations.
## Impact
Some actions can still be allowed after contract is paused.
## Code Snippet
Provided above
## Tool used

Manual Review

## Recommendation
Check `whenNotPaused` modifer for minting/redeeming/borrowing.

**Comment by sherlock-admin2** [comment]
1 comment(s) were left on this issue during the judging contest.

**auditsea** commented:
> Collaterals are controlled individually
