### ISSUE TITLE
cergyk - UbiquityPool::mintDollar/redeemDollar UbiquityPool does not keep track of minting/redemption fees

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-12-ubiquity-judging#73]
cergyk

high

# UbiquityPool::mintDollar/redeemDollar UbiquityPool does not keep track of minting/redemption fees

## Summary
When minting dollars or redeeming dollars, a fee is applied to be kept by the protocol. However there is no track of fees gathered by the contract by minting/redeeming, and these fees are still part of the freeBalance. This means the protocol will be unable to claim the fees associated to redeeming/minting 

## Vulnerability Detail
See in UbiquityPool::mintDollar (resp. redeemDollar) for the application of `mintingFee` (resp. `redeemingFee`):

https://github.com/sherlock-audit/2023-12-ubiquity/blob/main/ubiquity-dollar/packages/contracts/src/dollar/libraries/LibUbiquityPool.sol#L358-L364

https://github.com/sherlock-audit/2023-12-ubiquity/blob/main/ubiquity-dollar/packages/contracts/src/dollar/libraries/LibUbiquityPool.sol#L423-L429

The fees collected by the protocol are not kept track of, and are not discounted from the `freeCollateralBalance`:
https://github.com/sherlock-audit/2023-12-ubiquity/blob/main/ubiquity-dollar/packages/contracts/src/dollar/libraries/LibUbiquityPool.sol#L268-L276

This means that users are free to withdraw all DAI collateral, and the protocol won't be able to claim the fees collected in DAI.

## Impact
Protocol is losing the ability to claim collected fees

## Tool used

Manual Review

## Recommendation
Implement a variable `feeCollected` by collateral index, and remove fees collected from free balance to ensure the protocol will be able to claim the fee:

Duplicate of #36

**Comment by sherlock-admin2** [comment]
1 comment(s) were left on this issue during the judging contest.

**auditsea** commented:
> The goal of fee taken for mint/redeem is to hedge the risk of price deviation
