### ISSUE TITLE
nobody2018 - LibTWAPOracle.setPool may not be executed successfully

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-12-ubiquity-judging#77]
nobody2018

high

# LibTWAPOracle.setPool may not be executed successfully

## Summary

Before the core functions in UbiquityPoolFacet (`mintDollar`/`redeemDollar`/`collectRedemption`) can work properly, `TWAPOracleDollar3poolFacet.setPool` needs to be successfully executed. The logic inside this function has a check to ensure that [[the pair balance is perfect](https://github.com/sherlock-audit/2023-12-ubiquity/blob/main/ubiquity-dollar/packages/contracts/src/dollar/libraries/LibTWAPOracle.sol#L51)](https://github.com/sherlock-audit/2023-12-ubiquity/blob/main/ubiquity-dollar/packages/contracts/src/dollar/libraries/LibTWAPOracle.sol#L51), which can be broken by a malicious user by calling `MetaPool.exchange/remove_liquidity/add_liquidity`. As a result, `setPool` will never be called successfully.

## Vulnerability Detail

`TWAPOracleDollar3poolFacet.setPool` sub-calls [[LibTWAPOracle.setPool](https://github.com/sherlock-audit/2023-12-ubiquity/blob/main/ubiquity-dollar/packages/contracts/src/dollar/libraries/LibTWAPOracle.sol#L31)](https://github.com/sherlock-audit/2023-12-ubiquity/blob/main/ubiquity-dollar/packages/contracts/src/dollar/libraries/LibTWAPOracle.sol#L31).

```solidity
File: ubiquity-dollar\packages\contracts\src\dollar\libraries\LibTWAPOracle.sol
31:     function setPool(address _pool, address _curve3CRVToken1) internal {
......
45:         uint256 _reserve0 = uint112(IMetaPool(_pool).balances(0));
46:         uint256 _reserve1 = uint112(IMetaPool(_pool).balances(1));
47: 
48:         // ensure that there's liquidity in the pair
49:         require(_reserve0 != 0 && _reserve1 != 0, "TWAPOracle: NO_RESERVES");
50:         // ensure that pair balance is perfect
51:->       require(_reserve0 == _reserve1, "TWAPOracle: PAIR_UNBALANCED");
......
59:     }
```

`_pool` has 2 types of tokens: `token0`(dollarToken) and `token1`(curve3CRVToken).

L45, `_reserve0` is equal to the amount of `token0` recorded by `_pool`.

L46, `_reserve1` is equal to the amount of `token1` recorded by `_pool`.

L51, `_reserve0` must equal to `_reserve1`, otherwise, tx will revert.

Therefore, a malicious user could call `_pool.exchange` to break this check by front-running `TWAPOracleDollar3poolFacet.setPool`. Of course, you can also write a program to check whether the status of the pool meets `_reserve0 == _reserve1` to call `_pool.exchange`.

## Impact

pool can't be set, so the core functions of UbiquityPoolFacet are broken.

## Code Snippet

https://github.com/sherlock-audit/2023-12-ubiquity/blob/main/ubiquity-dollar/packages/contracts/src/dollar/libraries/LibTWAPOracle.sol#L51

## Tool used

Manual Review

## Recommendation

Please do not use `==` to ensure that pair balance is perfect.

Duplicate of #14

**Comment by sherlock-admin2** [comment]
1 comment(s) were left on this issue during the judging contest.

**auditsea** commented:
> The issue describes about DOSing setPool function by manipulating the Curve pool, but it's assumed that the Curve pool deployment, LP deposit, and setPool will be handled in one tx using multicall structure
