### ISSUE TITLE
0xG0P1 - Chainlink Oracle will return the wrong price for asset if underlying aggregator hits minAnswer

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-12-ubiquity-judging#81]
0xG0P1

medium

# Chainlink Oracle will return the wrong price for asset if underlying aggregator hits minAnswer

## Summary
Chainlink aggregators have a built in circuit breaker if the price of an asset goes outside of a predetermined price band. The result is that if an asset experiences a huge drop in value (i.e. LUNA crash) the price of the oracle will continue to return the minPrice instead of the actual price of the asset. This would allow user to continue borrowing with the asset but at the wrong price.
## Vulnerability Detail
ChainlinkFeedRegistry#latestRoundData pulls the associated aggregator and requests round data from it. ChainlinkAggregators have minPrice and maxPrice circuit breakers built into them. This means that if the price of the asset drops below the minPrice, the protocol will continue to value the token at minPrice instead of it's actual value. This will allow users to mint more tokens than the actual tokens that should be minted.

Example: TokenA has a minPrice of $1. The price of TokenA drops to $0.10. The aggregator still returns $1 allowing the user to borrow against TokenA as if it is $1 which is 10x it's actual value.
## Impact
Users can minted with more/Less tokens in the event of collateral asset crash.
## Code Snippet
https://github.com/sherlock-audit/2023-12-ubiquity/blob/main/ubiquity-dollar/packages/contracts/src/dollar/libraries/LibUbiquityPool.sol#L523-L562
## Tool used

Manual Review

## Recommendation
Chainlink Oracle should check the returned answer against the minPrice/maxPrice and revert if the answer is outside of the bounds:

`if (answer >= maxPrice or answer <= minPrice) revert();
`

Duplicate of #144

**Comment by sherlock-admin2** [comment]
1 comment(s) were left on this issue during the judging contest.

**auditsea** commented:
> The issue describes about not checking min/max value from Chainlink for data staleness, but this is not required
