### ISSUE TITLE
the-first-elder - TWAP oracle easily manipulated.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-12-ubiquity-judging#83]
the-first-elder

high

# TWAP oracle easily manipulated.

## Summary
TWAP oracle easily manipulated.

## Vulnerability Detail
The issue lies in the fact that the periodSize is set to 0, indicating that the oracle takes a new observation every single block. This configuration allows potential attackers to flood the TWAP oracle easily, enabling them to manipulate the reported price.

## Impact
The vulnerability poses a significant risk of price manipulation, potentially leading to inaccurate and unreliable TWAP values.

## Code Snippet
https://github.com/sherlock-audit/2023-12-ubiquity/blob/main/ubiquity-dollar/packages/contracts/src/dollar/libraries/LibTWAPOracle.sol#L74

## Tool used

Manual Review

## Recommendation
To address this vulnerability, it is strongly recommended to increase the periodSize to a value greater than 0. A standard value, such as 1800, is suggested. This adjustment will enhance the security of the TWAP oracle by reducing the frequency of observations and making it more resilient to manipulation. [link can be found here ](https://solodit.xyz/issues/h-04-oracle-periodsize-is-very-low-allowing-the-twap-price-to-be-easily-manipulated-code4rena-canto-canto-git).

Duplicate of #20

**Comment by sherlock-admin2** [comment]
1 comment(s) were left on this issue during the judging contest.

**auditsea** commented:
> The issue describes about TWAP can be manipulated because `update` function can be called anytime and by anyone, thus TWAP period can be as short as 1 block. It seems like a valid issue but after caeful consideration, it's noticed that the TWAP issue does not come from its period but the logic itself is incorrect, thus marking this as Invalid
