### ISSUE TITLE
osmanozdemir1 - The current Curve metapool factory and the metapool implementation contract does not have necessary TWAP functions

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-12-ubiquity-judging#87]
osmanozdemir1

high

# The current Curve metapool factory and the metapool implementation contract does not have necessary TWAP functions

## Summary
This protocol will deploy a metapool (Dollar-3CRVLP) using the Curve's metapool factory contract to be able to use this metapool as a price oracle. However, the currently active Curve metapool factory contract and the metapool implementation contracts are different from this protocol's previous deployments, and do not have necessary TWAP functionality. 

## Vulnerability Detail
This protocol gets collateral prices using the Chainlink oracle, and plans to determine the `UbiquityDollarToken` prices using the Curve metapool. The reason for that is the Chainlink oracle does not have a price feed for `UbiquityDollarToken`.

The protocol already has a deployed `Dollar-3CRVLP` metapool, which is deployed at [this address](https://etherscan.io/address/0x20955CB69Ae1515962177D164dfC9522feef567E#code) in June 2021. According to the [audit list](https://github.com/ubiquity/ubiquity-dollar/discussions/846) provided by the sponsor, this metapool will be redeployed with an upgradeability feature.

> There is the old Curve's `Dollar-3CRVLP` metapool but we will redeploy it because we plan to use the upgradeable Dollar token version (while the old metapool uses the old Dollar token).

As we can see [here](https://curve.readthedocs.io/ref-addresses.html#metapool-factory), the currently active Curve metapool factory address is: [0xB9fC157394Af804a3578134A6585C0dc9cc990d4](https://etherscan.io/address/0xB9fC157394Af804a3578134A6585C0dc9cc990d4).

The metapool implementation created with this factory contract is [0x213be373FDff327658139C7df330817DAD2d5bBE](https://etherscan.io/address/0x213be373fdff327658139c7df330817dad2d5bbe#code).

The latest metapool that is created with the current Curve metapool factory is created 36 days ago with this [transaction hash](https://etherscan.io/tx/0x3df74962bc58833ee086d4474b3dd5286801cc5d5f7c12be92626097fe3fe74c). You can see the implementation contract in the code section of [that metapool on etherscan](https://etherscan.io/address/0x79ce6be6ae0995b1c8ed3e8ae54de0e437dec8c3#code).

The issue is that the Curve factory and implementation contracts are updated by the Curve protocol, after Ubiquity's previous deployments in 2021. The new Curve implementation does not have TWAP functionality. It does not have the `get_price_cumulative_last()`, and the `get_twap_balances()` functions.

If the protocol deploys new `Dollar-3CRVLP` metapool using the Curve's current factory, it will not work as expected.

## Impact
The protocol will not work as expected.

## Code Snippet
https://github.com/sherlock-audit/2023-12-ubiquity/blob/main/ubiquity-dollar/packages/contracts/src/dollar/libraries/LibTWAPOracle.sol#L135

https://github.com/sherlock-audit/2023-12-ubiquity/blob/main/ubiquity-dollar/packages/contracts/src/dollar/libraries/LibTWAPOracle.sol#L77

## Tool used

Manual Review, Etherscan

## Recommendation
I am not sure what was the reason behind the Curve protocol changing both factory and implementation contracts. Ubiquity protocol may try to use the [old factory](https://etherscan.io/address/0x0959158b6040d32d04c301a72cbfd6b39e21c9ae) with [old implementation](https://etherscan.io/address/0x5f890841f657d90e081babdb532a05996af79fe6#code), but this might bring additional security issues depending on why they stop using them.

I would like to point out that the last metapool deployment using the old factory contract was performed more than 377 days ago (at the time of this submission), and it is never used since.

Duplicate of #201

**Comment by sherlock-admin2** [comment]
1 comment(s) were left on this issue during the judging contest.

**auditsea** commented:
> Protocol team will re-deploy the contract based on their needs, so basically out of scope
