### ISSUE TITLE
blutorque - User can fail to `collectRedemption` for the collateral token(e.g. USDC, USDT), if got blacklisted by such tokens

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-12-ubiquity-judging#9]
blutorque

medium

# User can fail to `collectRedemption` for the collateral token(e.g. USDC, USDT), if got blacklisted by such tokens

## Summary
User can fail to `collectRedemption` for the collateral token(e.g. USDC, USDT), if got blacklisted by such tokens 
## Vulnerability Detail
When `addCollateralToken`, the missingDecimals field for that token is also updated, suggesting the possibility that the added token can have a decimal value other than 18.

Some tokens such as USDC, USDT have a blocklist feature. If an address got blocked then transfers to and from will be forbidden for that address. The `collectRedemption` transferring the user `redeemCollateralBalances` to the same address as `msg.sender`. Therefore, no way user can claim his collateral if got blacklisted during the redemption. 

## Impact
User with `redeemCollateralBalances != 0` will fail to `collectRedemption`, losing their collateral until unblock.

## Code Snippet
https://github.com/sherlock-audit/2023-12-ubiquity/blob/d9c39e8dfd5601e7e8db2e4b3390e7d8dff42a8e/ubiquity-dollar/packages/contracts/src/dollar/libraries/LibUbiquityPool.sol#L514-L515
## Tool used

Manual Review

## Recommendation
Add an extra paramter `to` address to withdraw to, 
```solidity
    function collectRedemption(
        uint256 collateralIndex,
	address to
    ) internal returns (uint256 collateralAmount) {
       ...SNIP...

        // send out the tokens
        if (sendCollateral) {
            IERC20(poolStorage.collateralAddresses[collateralIndex])
                .safeTransfer(to, collateralAmount);
        }
    }
```

**Comment by sherlock-admin2** [comment]
1 comment(s) were left on this issue during the judging contest.

**auditsea** commented:
> It depends on the user's action, nothing related to the protocol
