### ISSUE TITLE
rvierdiiev - AccessControlFacet doesn't have ability to set admin for the role

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2023-12-ubiquity-judging#90]
rvierdiiev

medium

# AccessControlFacet doesn't have ability to set admin for the role

## Summary
AccessControlFacet doesn't have ability to set admin for the role.
## Vulnerability Detail
`AccessControlFacet` is created to allow protocol manage different roles. Facet extends `AccessControlInternal`, which has different methods and uses `LibAccessControl` library to store executed roles actions.

While `LibAccessControl` library [has `setRoleAdmin` function](https://github.com/sherlock-audit/2023-12-ubiquity/blob/main/ubiquity-dollar/packages/contracts/src/dollar/libraries/LibAccessControl.sol#L140-L144), both `AccessControlFacet` and `AccessControlInternal` don't use it. And as result it's not possible to set admin for the role.

Because of that only default admin will be used as parent role and protocol will not be able to granulary manage their roles.
## Impact
Admin for the role can't be set.
## Code Snippet
Provided above
## Tool used

Manual Review

## Recommendation
Add function on the facet that will set admin for the role.

**Comment by sherlock-admin2** [comment]
1 comment(s) were left on this issue during the judging contest.

**auditsea** commented:
> Owner is set as a default admin, it should work

**Comment by 0xArz** [comment]
Escalate

I think this should be a low/qa as the impact here is not severe. There is no loss of funds and the roles can always be managed by the DEFAULT_ADMIN_ROLE which is set

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> I think this should be a low/qa as the impact here is not severe. There is no loss of funds and the roles can always be managed by the DEFAULT_ADMIN_ROLE which is set 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by nevillehuang** [comment]
@0xArz you might want to reconsider you escalation based on this comment [here](https://github.com/sherlock-audit/2023-12-ubiquity-judging/issues/90#issuecomment-1895166805). Based on sherlock rules, This breaks intended contract functionality, so it will likely be warranted medium severity even if there is no loss of funds

**Comment by molecula451** [comment]
We fixed this one check: https://github.com/sherlock-audit/2023-12-ubiquity-judging/issues/90#issuecomment-1901009213

**Comment by molecula451** [comment]
we will leave it as a medium

**Comment by 0xArz** [comment]
> @0xArz you might want to reconsider you escalation based on this comment [here](https://github.com/sherlock-audit/2023-12-ubiquity-judging/issues/90#issuecomment-1895166805). Based on sherlock medium severity rules, This breaks intended contract functionality, so it will likely be warranted medium severity even if there is no loss of funds

I get that yeah but it doesnt break intended contract functionality if the admin of all roles is the DEFAULT_ADMIN_ROLE which will always be able to manage the roles and no fix is needed. Having seperate admins to manage the roles would ofc be good but i believe this should be a low so i will keep my escalation.

**Comment by 0xhsp** [comment]
> I get that yeah but it doesnt break intended contract functionality if the admin of all roles is the DEFAULT_ADMIN_ROLE which will always be able to manage the roles and no fix is needed. Having seperate admins to manage the roles would ofc be good but i believe this should be a low so i will keep my escalation.

The **intended contract functionality** is **setting admin for each role**, not just **managing the roles**, so this is a valid medium

**Comment by juntzhan** [comment]
> I get that yeah but it doesnt break intended contract functionality if the admin of all roles is the DEFAULT_ADMIN_ROLE which will always be able to manage the roles and no fix is needed. Having seperate admins to manage the roles would ofc be good but i believe this should be a low so i will keep my escalation.

The **intended contract functionality** is **setting admin for each role**, not just **managing the roles**, so this is a valid medium.

**Comment by 0xnirlin** [comment]
@rvierdiyev I tried to create a high issue, combining this access control issue with what I though is another issue with the deployment, which turned out after I did bit of digging to be wrong. But that does not change the fact that I tried to built the whole point on the fact that `setRoleAdmin` is not available which is indeed an issue. 

```
And also setRoleAdmin function from LibAccessControl.sol function is not exposed in facet
```

The line you are referring to is this, which is also the issue that is presented in this report.

**Comment by rvierdiyev** [comment]
> The line you are referring to is this, which is also the issue that is presented in this report.

this is true.

**Comment by 0xArz** [comment]
> > I get that yeah but it doesnt break intended contract functionality if the admin of all roles is the DEFAULT_ADMIN_ROLE which will always be able to manage the roles and no fix is needed. Having seperate admins to manage the roles would ofc be good but i believe this should be a low so i will keep my escalation.
> 
> The **intended contract functionality** is **setting admin for each role**, not just **managing the roles**, so this is a valid medium.

Disagree, these admins are set in order to manage the role so managing the roles is the intended functionality which still works because the default admin role can always manage it. If the default admin didnt exist then i would agree with a medium because revoking the role would not work and etc. Dont want to spend time arguing here so lets just leave it to the judge.

**Comment by 0xnirlin** [comment]
Giving the admin access for a role is the intended functionality, the intent is shown in the library, and the devs themselves agree to that, they missed it in exposing the facet. before submitting I discussed it with the devs and they didn't know that this it is missed.

**Comment by 0xLogos** [comment]
> Giving the admin access for a role is the intended functionality, the intent is shown in the library, and the devs themselves agree to that, they missed it in exposing the facet. before submitting I discussed it with the devs and they didn't know that this it is missed.

Agree with Arz. As far as I know, all that was publicly known during the audit was that the library had this function. It seems to me that this is not enough to consider this funcionality intended.

**Comment by 0xnirlin** [comment]
@0xLogos but sponsors think otherwise 

![Group 33](https://github.com/sherlock-audit/2023-12-ubiquity-judging/assets/68193826/d1b206c2-212e-44c5-9094-5ecbb4cf2918)

**Comment by 0xLogos** [comment]
I mean "not enough to consider this funcionality intended" based on public information during audit.

From [here](https://docs.sherlock.xyz/audits/judging/judging#iii.-some-standards-observed) p.6

> Discord messages or DM screenshots are not considered sources of truth while judging an issue/escalation especially if they are conflicting with the contest README.

**Comment by 0xnirlin** [comment]
Will leave it to judges after this last comment, I posted a screenshot because you were assuming that it is not intended functionality, nothing as such is mentioned in the ReadMe and that further weakens your argument.

**Comment by CergyK** [comment]
> Escalate
> 
> I think this should be a low/qa as the impact here is not severe. There is no loss of funds and the roles can always be managed by the DEFAULT_ADMIN_ROLE which is set

Would like to add that this is not a bug, it is missing admin functionality.
Which could be easily added by doing a DiamondCut (upgrade). Since adding a role admin is not a frequent action, doing the upgrade to add the feature when/if needed is only a minor inconvenience

**Comment by 0xnirlin** [comment]
Then according to this argument, every bug in this contract that doesn't lead into loss of funds is a minor inconvenience and one upgrade away from being resolved. Even the permanent DOS can be reversed.

**Comment by CergyK** [comment]
> Then according to this argument, every bug in this contract that doesn't lead into loss of funds is a minor inconvenience and one upgrade away from being resolved. Even the permanent DOS can be reversed.

I won't argue further, but I think the fact it only impacts admin capacity should be taken in consideration. Of course if a bug affects the end-user in any way, upgradeability should not be a pass.

**Comment by molecula451** [comment]
> Would like to add that this is not a bug, it is missing admin functionality. Which could be easily added by doing a DiamondCut (upgrade). Since adding a role admin is not a frequent action, doing the upgrade to add the feature when/if needed is only a minor inconvenience

btw the contracts are not deployed, we are not "upgrading" we fixing by PRs

**Comment by Czar102** [comment]
Great points made [here](https://github.com/sherlock-audit/2023-12-ubiquity-judging/issues/90#issuecomment-1911964384) and [here](https://github.com/sherlock-audit/2023-12-ubiquity-judging/issues/90#issuecomment-1914441905), I fully agree with them.

Planning to consider this a low severity issue.

**Comment by nevillehuang** [comment]
There are heavy assumptions from both sides of the argument on the protocol intentions, but it is a fact that they fixed the issue without an upgrade, so we can all come to a consensus that ultimately, this does break the final outcome of what the protocol intended, that is they want to assign multiple admins for different roles. 

However, there is always the argument of unused functionality not impacting the overall protocols functionality, and for that reason, if @Czar102 or @Evert0x invalidates this, I would have to respect enforcement of sherlock rules.

**Comment by Evert0x** [comment]
Still planning to accept escalation and close issue.

There is no issue being fixed, new functionality is being added

**Comment by sherlock-admin2** [comment]
The escalations could not be resolved because the issue failed the following checks:

- Expected issue to not have any duplicates. Existing duplicates: #116, #205
- Expected severity: **false**. Actual severity: **medium**.
- Expected issue to be **open**. Actual issue is **closed**.
- [0xArz's escalation](https://github.com/sherlock-audit/2023-12-ubiquity-judging/issues/90/#issuecomment-1908635738) could not be resolved, because it has 0 or more than 1 judge reactions.

**Comment by pavlovcik** [comment]
@molecula451 https://github.com/sherlock-audit/2023-12-ubiquity-judging/pull/232

**Comment by molecula451** [comment]
@Evert0x can you open - reopen this one

**Comment by pavlovcik** [comment]
> ```diff
> ! action has an uncaught error
> ```

I think this is `members=read` permissions were not granted, so it can't see who's part of the collaborators to calculate collaborator incentives.

**Comment by 0x4007** [comment]
@molecula451 its the character length bug. I can try to push a workaround real quick. 
- https://github.com/ubiquibot/comment-incentives/issues/19

**Comment by molecula451** [comment]
@pavlovcik go ahead

**Comment by 0x4007** [comment]
In the future @molecula451 be sure to link a pull request for assignees to get their credit.

**Comment by molecula451** [comment]
i think we can do it again, the bot won't trigger for the comments? @pavlovcik

**Comment by molecula451** [comment]
looks like gitcoindev PR comment did not hook here https://github.com/ubiquity/ubiquity-dollar/pull/880#issue-2091040430

**Comment by molecula451** [comment]
yeah pavlovick it's not hooking cross-side PR comment, tested with different keywords @pavlovcik

**Comment by 0x4007** [comment]
> yeah pavlovick it's not hooking cross-side PR comment, tested with different keywords @pavlovcik 

The pull request must be linked to this issue. It currently is not that's why the bot did not associate the conversation.

**Comment by molecula451** [comment]
it's looking like sherklock admin level because gitcoindev commented "fixes" and it should do it cross-side, also we can't (ubiquity) manually link PRs here

![image_2024-02-17_081157261](https://github.com/sherlock-audit/2023-12-ubiquity-judging/assets/41552663/b0bfa67e-c208-4207-8eff-6d10dabb217e)

**Comment by sherlock-admin** [comment]
The protocol team fixed this issue in PR/commit https://github.com/ubiquity/ubiquity-dollar/pull/880.

**Comment by sherlock-admin** [comment]
The Lead Senior Watson signed off on the fix.
