### ISSUE TITLE
rvierdiiev - No ability to withdraw fees from LibUbiquityPool

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-12-ubiquity-judging#91]
rvierdiiev

medium

# No ability to withdraw fees from LibUbiquityPool

## Summary
Currently there is no ability to withdraw fees from LibUbiquityPool as such functionality is not created.
## Vulnerability Detail
User that mint or redeem UbiquityDollar [pays fee for each action](https://github.com/sherlock-audit/2023-12-ubiquity/blob/main/ubiquity-dollar/packages/contracts/src/dollar/libraries/LibUbiquityPool.sol#L358-L364). This fee in form of collateral token is supposed to be used by protocol.

Currently there are several problems with this functionality:
- protocol doesn't have any functionality that allows to withdraw accrued fees.
- library doesn't track exact amount of accrued fee as they come in form of different assets(depends on what user uses as collateral for the mint/redeem)
- `amoMinter` can borrow protocol fees.
## Impact
No ability to track and withdraw fees.
## Code Snippet
https://github.com/sherlock-audit/2023-12-ubiquity/blob/main/ubiquity-dollar/packages/contracts/src/dollar/libraries/LibUbiquityPool.sol#L358-L364
https://github.com/sherlock-audit/2023-12-ubiquity/blob/main/ubiquity-dollar/packages/contracts/src/dollar/libraries/LibUbiquityPool.sol#L423-L429
## Tool used

Manual Review

## Recommendation
Track fees and create possibility to withdraw them.

Duplicate of #36

**Comment by sherlock-admin2** [comment]
1 comment(s) were left on this issue during the judging contest.

**auditsea** commented:
> The goal of fee taken for mint/redeem is to hedge the risk of price deviation
